version: '2'
messages:
  $i18n: locales.yml
template:
  name: "Develop a Code Engine app"
  description: "With this toolchain, you can develop, and deploy a Code Engine application securely into a shared, multi-tenant Kubernetes cluster on IBM Cloud. By default, the toolchain uses a sample Node.js \"Hello World\" app, but you can link to your own GitHub repository instead. The toolchain is preconfigured for continuous delivery with [Vulnerability Advisor](https://cloud.ibm.com/docs/services/va?topic=va-va_index), source control, issue tracking, and online editing.\n\n You can manage your Code Engine projects and applications in the [console](https://cloud.ibm.com/knative).\n\nThe toolchain uses tools that are part of the Continuous Delivery service. If an instance of that service isn't already in the selected resource group or organization, when you click **Create**, it is automatically added with the free [Lite](/catalog/services/continuous-delivery/) plan selected.\n\nTo get started, click **Create**."
  header: '![](toolchain.svg?localize)'
  icon: knative.svg
  required:
    - build
    - repo
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
        $env.branch ?
          '[' + $env.branch + ']('+ $env.repository + '/tree/' + $env.branch + ')' :
          '[master]('+ $env.repository + '/tree/master)
toolchain:
  name: >
    $env.toolchainName ? '{{toolchainName}}' :
      'code-engine-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  repo:
    service_id: >
      $env.source_provider ? $env.source_provider : 'hostedgit'
    parameters:
      repo_name: '{{toolchain.name}}'
      repo_url: >
        $env.type === 'link' ? $env.app_repo :
          $env.sourceZipUrl ? '{{sourceZipUrl}}' :
            'http://github.com/IBM/java-spring-app'
      source_repo_url: >
        $env.type === 'fork' || $env.type === 'clone' ? $env.app_repo :
          $env.sourceZipUrl ? '{{sourceZipUrl}}' : 'http://github.com/IBM/java-spring-app'
      type: $env.type || 'clone'
      has_issues: true
      enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          APP_NAME: '{{form.pipeline.parameters.app-name}}'
          IMAGE_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          CODE_ENGINE_PROJECT: '{{form.pipeline.parameters.code-engine-project}}'
          CODE_ENGINE_REGION: '{{form.pipeline.parameters.code-engine-region}}'
          CODE_ENGINE_RESOURCE_GROUP: '{{form.pipeline.parameters.code-engine-resource-group}}'
          SERVICE_INSTANCE_NAMES: '{{form.pipeline.parameters.service-instance-names}}'
        execute: true
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      app-name: >
        $env.appName ?
          '{{appName}}' : '{{services.repo.parameters.repo_name}}'
      registry-region: '{{registryRegion}}'
      registry-namespace: '{{registryNamespace}}'
      api-key: '{{apiKey}}'
      code-engine-project: '{{codeEngineProject}}'
      code-engine-region: '{{codeEngineRegion}}'
      code-engine-resource-group: '{{codeEngineResourceGroup}}'
      service-instance-names: '{{serviceInstanceNames}}'
    schema:
      $ref: form-schema.json
